const data = {
  rooms: [
    {
      name: 'Living Room',
      km: '1034',
      value: '12',
      color: '#05C985',
      points: [
        { period: 'JAN', value: 100 },
        { period: 'FEB', value: 310 },
        { period: 'MAR', value: 510 },
        { period: 'APR', value: 595 },
        { period: 'MAY', value: 505 },
        { period: 'JUN', value: 395 },
        { period: 'JUL', value: 355 },
        { period: 'AUG', value: 500 },
        { period: 'SEP', value: 300 },
        { period: 'OCT', value: 400 },
        { period: 'NOV', value: 405 },
        { period: 'DEC', value: 395 },
      ],
    },
    {
      name: 'Studio',
      km: '1034',
      value: '16',
      color: '#ffab4f',
      points: [
        { period: 'JAN', value: 100 },
        { period: 'FEB', value: 400 },
        { period: 'MAR', value: 420 },
        { period: 'APR', value: 400 },
        { period: 'MAY', value: 415 },
        { period: 'JUN', value: 400 },
        { period: 'JUL', value: 460 },
        { period: 'AUG', value: 430 },
        { period: 'SEP', value: 480 },
        { period: 'OCT', value: 475 },
        { period: 'NOV', value: 340 },
        { period: 'DEC', value: 460 },
      ],
    },
    {
      name: "Kid's Bedroom",
      km: '1034',
      value: '32',
      color: '#EE423D',
      points: [
        { period: 'JAN', value: 100 },
        { period: 'FEB', value: 280 },
        { period: 'MAR', value: 315 },
        { period: 'APR', value: 305 },
        { period: 'MAY', value: 315 },
        { period: 'JUN', value: 295 },
        { period: 'JUL', value: 310 },
        { period: 'AUG', value: 305 },
        { period: 'SEP', value: 400 },
        { period: 'OCT', value: 300 },
        { period: 'NOV', value: 260 },
        { period: 'DEC', value: 300 },
      ],
    },
    {
      name: 'Kitchen',
      km: '1034',
      value: '18',
      color: '#843FA0',
      points: [
        { period: 'JAN', value: 100 },
        { period: 'FEB', value: 270 },
        { period: 'MAR', value: 310 },
        { period: 'APR', value: 300 },
        { period: 'MAY', value: 315 },
        { period: 'JUN', value: 295 },
        { period: 'JUL', value: 315 },
        { period: 'AUG', value: 310 },
        { period: 'SEP', value: 400 },
        { period: 'OCT', value: 300 },
        { period: 'NOV', value: 290 },
        { period: 'DEC', value: 300 },
      ],
    },
  ],
}

export default data
